In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [1]:
!pip3 install -U ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.6-py3-none-any.whl.metadata (5.3 kB)
Downloading ucimlrepo-0.0.6-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.6

In [18]:
from ucimlrepo import fetch_ucirepo, list_available_datasets,list_available_datasets1

import pprint

## List Available Datasets
### **Print a list of datasets that can be imported via `fetch_ucirepo`**

In [20]:
list_available_datasets()
list = list_available_datasets1()
#list_available_datasets(filter='aim-ahead')   # only list datasets for AIM-AHEAD project
#list_available_datasets(search='diabe')

-------------------------------------
The following datasets are available:
-------------------------------------
Dataset Name                                                                            ID
------------                                                                            --
Abalone                                                                                 1
Adult                                                                                   2
Annealing                                                                               3
Audiology (Standardized)                                                                8
Auto MPG                                                                                9
Automobile                                                                              10
Balance Scale                                                                           12
Balloons                                                                                13
Breast Cancer                                                                           14
Breast Cancer Wisconsin (Original)                                                      15
Breast Cancer Wisconsin (Prognostic)                                                    16
Breast Cancer Wisconsin (Diagnostic)                                                    17
Pittsburgh Bridges                                                                      18
Car Evaluation                                                                          19
Census Income                                                                           20
Chess (King-Rook vs. King-Pawn)                                                         22
Chess (King-Rook vs. King)                                                              23
Connect-4                                                                               26
Credit Approval                                                                         27
Japanese Credit Screening                                                               28
Computer Hardware                                                                       29
Contraceptive Method Choice                                                             30
Covertype                                                                               31
Cylinder Bands                                                                          32
Dermatology                                                                             33
Echocardiogram                                                                          38
Ecoli                                                                                   39
Flags                                                                                   40
Glass Identification                                                                    42
Haberman's Survival                                                                     43
Hayes-Roth                                                                              44
Heart Disease                                                                           45
Hepatitis                                                                               46
Horse Colic                                                                             47
Image Segmentation                                                                      50
Ionosphere                                                                              52
Iris                                                                                    53
ISOLET                                                                                  54
Lenses                                                                                  58
Letter Recognition                                                                      59
Liver Disorders                                                                         60
Lung Cancer                                                                             62
Lymphography                                                                            63
Molecular Biology (Splice-junction Gene Sequences)                                      69
MONK's Problems                                                                         70
Mushroom                                                                                73
Musk (Version 1)                                                                        74
Musk (Version 2)                                                                        75
Nursery                                                                                 76
Page Blocks Classification                                                              78
Optical Recognition of Handwritten Digits                                               80
Pen-Based Recognition of Handwritten Digits                                             81
Post-Operative Patient                                                                  82
Primary Tumor                                                                           83
Servo                                                                                   87
Shuttle Landing Control                                                                 88
Solar Flare                                                                             89
Soybean (Large)                                                                         90
Soybean (Small)                                                                         91
Challenger USA Space Shuttle O-Ring                                                     92
Spambase                                                                                94
SPECT Heart                                                                             95
SPECTF Heart                                                                            96
Tic-Tac-Toe Endgame                                                                     101
Congressional Voting Records                                                            105
Waveform Database Generator (Version 1)                                                 107
Wine                                                                                    109
Yeast                                                                                   110
Zoo                                                                                     111
US Census Data (1990)                                                                   116
Census-Income (KDD)                                                                     117
El Nino                                                                                 122
Statlog (Australian Credit Approval)                                                    143
Statlog (German Credit Data)                                                            144
Statlog (Heart)                                                                         145
Statlog (Landsat Satellite)                                                             146
Statlog (Image Segmentation)                                                            147
Statlog (Shuttle)                                                                       148
Statlog (Vehicle Silhouettes)                                                           149
Connectionist Bench (Sonar, Mines vs. Rocks)                                            151
Cloud                                                                                   155
Poker Hand                                                                              158
MAGIC Gamma Telescope                                                                   159
Mammographic Mass                                                                       161
Forest Fires                                                                            162
Concrete Compressive Strength                                                           165
Ozone Level Detection                                                                   172
Parkinsons                                                                              174
Blood Transfusion Service Center                                                        176
Communities and Crime                                                                   183
Acute Inflammations                                                                     184
Wine Quality                                                                            186
Parkinsons Telemonitoring                                                               189
Cardiotocography                                                                        193
Steel Plates Faults                                                                     198
Communities and Crime Unnormalized                                                      211
Vertebral Column                                                                        212
Bank Marketing                                                                          222
ILPD (Indian Liver Patient Dataset)                                                     225
Skin Segmentation                                                                       229
Individual Household Electric Power Consumption                                         235
Energy Efficiency                                                                       242
Fertility                                                                               244
ISTANBUL STOCK EXCHANGE                                                                 247
User Knowledge Modeling                                                                 257
EEG Eye State                                                                           264
Banknote Authentication                                                                 267
Gas Sensor Array Drift at Different Concentrations                                      270
Bike Sharing                                                                            275
Thoracic Surgery Data                                                                   277
Airfoil Self-Noise                                                                      291
Wholesale customers                                                                     292
Combined Cycle Power Plant                                                              294
Diabetes 130-US Hospitals for Years 1999-2008                                           296
Tennis Major Tournament Match Statistics                                                300
Dow Jones Index                                                                         312
Student Performance                                                                     320
Phishing Websites                                                                       327
Diabetic Retinopathy Debrecen                                                           329
Online News Popularity                                                                  332
Chronic Kidney Disease                                                                  336
Mice Protein Expression                                                                 342
Default of Credit Card Clients                                                          350
Online Retail                                                                           352
Occupancy Detection                                                                     357
Air Quality                                                                             360
Polish Companies Bankruptcy                                                             365
Dota2 Games Results                                                                     367
Facebook Metrics                                                                        368
HTRU2                                                                                   372
Drug Consumption (Quantified)                                                           373
Appliances Energy Prediction                                                            374
Website Phishing                                                                        379
YouTube Spam Collection                                                                 380
Beijing PM2.5                                                                           381
Cervical Cancer (Risk Factors)                                                          383
Stock Portfolio Performance                                                             390
Sales Transactions Weekly                                                               396
Daily Demand Forecasting Orders                                                         409
Autistic Spectrum Disorder Screening Data for Children                                  419
Autism Screening Adult                                                                  426
Absenteeism at work                                                                     445
Breast Cancer Coimbra                                                                   451
Drug Reviews (Druglib.com)                                                              461
Drug Reviews (Drugs.com)                                                                462
Superconductivty Data                                                                   464
Student Academics Performance                                                           467
Online Shoppers Purchasing Intention Dataset                                            468
Electrical Grid Stability Simulated Data                                                471
Real Estate Valuation                                                                   477
Travel Reviews                                                                          484
Travel Review Ratings                                                                   485
Facebook Live Sellers in Thailand                                                       488
Metro Interstate Traffic Volume                                                         492
Hepatitis C Virus (HCV) for Egyptian patients                                           503
Heart Failure Clinical Records                                                          519
Early Stage Diabetes Risk Prediction                                                    529
Pedestrians in Traffic                                                                  536
Cervical Cancer Behavior Risk                                                           537
Estimation of Obesity Levels Based On Eating Habits and Physical Condition              544
Rice (Cammeo and Osmancik)                                                              545
Algerian Forest Fires                                                                   547
Gas Turbine CO and NOx Emission Data Set                                                551
Apartment for Rent Classified                                                           555
Seoul Bike Sharing Demand                                                               560
Iranian Churn                                                                           563
Bone marrow transplant: children                                                        565
COVID-19 Surveillance                                                                   567
HCV data                                                                                571
Taiwanese Bankruptcy Prediction                                                         572
Myocardial infarction complications                                                     579
Student Performance on an Entrance Examination                                          582
Gender by Name                                                                          591
Productivity Prediction of Garment Employees                                            597
AI4I 2020 Predictive Maintenance Dataset                                                601
Dry Bean                                                                                602
In-Vehicle Coupon Recommendation                                                        603
Predict Students' Dropout and Academic Success                                          697
Auction Verification                                                                    713
NATICUSdroid (Android Permissions)                                                      722
Toxicity                                                                                728
DARWIN                                                                                  732
Accelerometer Gyro Mobile Phone                                                         755
Glioma Grading Clinical and Mutation Features                                           759
Multivariate Gait Data                                                                  760
Land Mines                                                                              763
Single Elder Home Monitoring: Gas and Position                                          799
Sepsis Survival Minimal Clinical Records                                                827
Secondary Mushroom                                                                      848
Power Consumption of Tetouan City                                                       849
Raisin                                                                                  850
Steel Industry Energy Consumption                                                       851
Higher Education Students Performance Evaluation                                        856
Risk Factor Prediction of Chronic Kidney Disease                                        857
Maternal Health Risk                                                                    863
Room Occupancy Estimation                                                               864
Cirrhosis Patient Survival Prediction                                                   878
SUPPORT2                                                                                880
National Health and Nutrition Health Survey 2013-2014 (NHANES) Age Prediction Subset    887
AIDS Clinical Trials Group Study 175                                                    890
CDC Diabetes Health Indicators                                                          891
Recipe Reviews and User Feedback                                                        911
Forty Soybean Cultivars from Subsequent Harvests                                        913
Differentiated Thyroid Cancer Recurrence                                                915
Infrared Thermography Temperature                                                       925
National Poll on Healthy Aging (NPHA)                                                   936
Regensburg Pediatric Appendicitis                                                       938
RT-IoT2022                                                                              942
PhiUSIIL Phishing URL (Website)                                                         967

In [6]:
print(datasets)

None

### **Should not work for datasets that are not part of the list**

In [5]:
try:
    fetch_ucirepo(name='defungi')
    # # test invalid inputs
    # fetch_ucirepo(name='heart diseaseeeee') 
    # fetch_ucirepo(id=10000)
except Exception as e:
    print(e)

-------------------------------------
The following datasets are available:
-------------------------------------
Dataset Name                                             ID
------------                                             --
Heart Disease                                            45
Parkinsons Telemonitoring                                189
Thoracic Surgery Data                                    277
Diabetes 130-US hospitals for years 1999-2008            296
Diabetic Retinopathy Debrecen                            329
HCV data                                                 571
Myocardial infarction complications                      579
Glioma Grading Clinical and Mutation Features Dataset    759
Sepsis Survival Minimal Clinical Records                 827

"iris" dataset (id=53) exists in the repository, but is not available for import.

## **Import dataset by ID**

In [3]:
sepsis = fetch_ucirepo(id=827)

### **Metadata**

In [8]:
pprint.pp(sepsis.metadata)

{'uci_id': 827,
 'name': 'Sepsis Survival Minimal Clinical Records',
 'repository_url': 'https://archive.ics.uci.edu/dataset/827/sepsis+survival+minimal+clinical+records',
 'data_url': 'https://archive.ics.uci.edu/static/public/827/data.csv',
 'abstract': 'This dataset collection contains minimal health records of '
             '110,204 admissions (primary cohort), 19,051 admissions (study '
             'cohort), and 137 admissions (validation cohort) of patients who '
             'had sepsis.',
 'area': 'Life Science',
 'tasks': ['Classification'],
 'characteristics': ['Multivariate'],
 'num_instances': 110341,
 'num_features': 3,
 'attribute_types': ['Integer'],
 'target_col': ['hospital_outcome_1alive_0dead'],
 'index_col': None,
 'has_missing_values': 'no',
 'missing_values_symbol': None,
 'year_of_dataset_creation': 2020,
 'last_updated': 'Wed Aug 02 2023',
 'dataset_doi': '10.24432/C53C8N',
 'creators': ['Davide Chicco', 'Giuseppe Jurman'],
 'intro_paper': {'title': 'Survival prediction of patients with sepsis from '
                          'age, sex, and septic episode number alone',
                 'authors': 'D. Chicco, Giuseppe Jurman',
                 'published_in': 'Scientific Reports',
                 'year': 2020,
                 'url': 'https://www.semanticscholar.org/paper/423a47a81777e46430b6ae463e3f39574bfa780d',
                 'doi': None,
                 '__class__': <class 'ucimlrepo.dotdict.dotdict'>},
 'additional_info': {'summary': 'Primary cohort from Norway:\n'
                                '4 features for 110,204 patient admissions\n'
                                'file: '
                                "'s41598-020-73558-3_sepsis_survival_primary_cohort.csv'\n"
                                '\n'
                                'Study cohort (subset of the primary cohort) '
                                'from Norway:\n'
                                '4 features for 19,051 patient admissions\n'
                                'file: '
                                "'s41598-020-73558-3_sepsis_survival_study_cohort.csv'\n"
                                '\n'
                                'Validation cohort from South Korea:\n'
                                '4 features for 137 patients\n'
                                'file: '
                                "'s41598-020-73558-3_sepsis_survival_validation_cohort.csv'",
                     'purpose': None,
                     'funded_by': None,
                     'instances_represent': None,
                     'recommended_data_splits': None,
                     'sensitive_data': None,
                     'preprocessing_description': None,
                     'software_available': None,
                     'used_for': None,
                     'attribute_info': 'Four (4) clinical features:\n'
                                       '- age_years: integer\n'
                                       '- sex_0male_1female: binary\n'
                                       '- episode_number: integer\n'
                                       '- hospital_outcome_1alive_0dead: '
                                       'boolean',
                     'citation': 'Davide Chicco, Giuseppe Jurman, â€œSurvival '
                                 'prediction of patients with sepsis from age, '
                                 'sex, and septic episode number aloneâ€\x9d. '
                                 'Scientific Reports 10, 17156 (2020)',
                     '__class__': <class 'ucimlrepo.dotdict.dotdict'>},
 '__class__': <class 'ucimlrepo.dotdict.dotdict'>}

In [13]:
sepsis.metadata.target_col

['hospital_outcome_1alive_0dead']

In [8]:
sepsis.metadata.intro_paper.title

'Survival prediction of patients with sepsis from age, sex, and septic episode number alone'

In [9]:
sepsis.metadata.additional_info.summary

"Primary cohort from Norway:\n4 features for 110,204 patient admissions\nfile: 's41598-020-73558-3_sepsis_survival_primary_cohort.csv'\n\nStudy cohort (subset of the primary cohort) from Norway:\n4 features for 19,051 patient admissions\nfile: 's41598-020-73558-3_sepsis_survival_study_cohort.csv'\n\nValidation cohort from South Korea:\n4 features for 137 patients\nfile: 's41598-020-73558-3_sepsis_survival_validation_cohort.csv'"

### **Data**
**IDs, features, and targets are included as separate dataframes, along with an "original" that combines all of them.**

In [10]:
sepsis.data.features

        age_years  sex_0male_1female  episode_number
0              21                  1               1
1              20                  1               1
2              21                  1               1
3              77                  0               1
4              72                  0               1
...           ...                ...             ...
110336         47                  0               1
110337         50                  0               1
110338         62                  0               1
110339         58                  0               1
110340         55                  1               1

[110341 rows x 3 columns]

In [23]:
sepsis.data.targets

        hospital_outcome_1alive_0dead
0                                   1
1                                   1
2                                   1
3                                   1
4                                   1
...                               ...
110336                              1
110337                              0
110338                              1
110339                              0
110340                              1

[110341 rows x 1 columns]

In [24]:
sepsis.data.ids   # this dataset no IDs

In [25]:
sepsis.data.original

,age_years,sex_0male_1female,episode_number,hospital_outcome_1alive_0dead
0,21,1,1,1
1,20,1,1,1
2,21,1,1,1
3,77,0,1,1
4,72,0,1,1
...,...,...,...,...
110336,47,0,1,1
110337,50,0,1,0
110338,62,0,1,1
110339,58,0,1,0
110340,55,1,1,1

In [26]:
sepsis.data.headers

Index(['age_years', 'sex_0male_1female', 'episode_number',
       'hospital_outcome_1alive_0dead'],
      dtype='object')

### **Variable Info**

**Displayed in a dataframe format**

In [9]:
sepsis.variables

,name,role,type,demographic,description,units,missing_values
0,age_years,Feature,Integer,None,None,None,no
1,sex_0male_1female,Feature,Binary,None,None,None,no
2,episode_number,Feature,Integer,None,None,None,no
3,hospital_outcome_1alive_0dead,Target,Binary,None,None,None,no

## Import by Name

In [27]:
glioma = fetch_ucirepo(name='glioma')
glioma.data.features

,Gender,Age_at_diagnosis,Race,IDH1,TP53,ATRX,PTEN,EGFR,CIC,MUC16,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
0,0,51.30,white,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,38.72,white,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,35.17,white,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,32.78,white,1,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,0,31.51,white,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,1,77.89,white,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
835,0,85.18,white,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
836,1,77.49,white,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
837,0,63.33,white,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
838,0,76.61,black or african american,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=189) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables)

{'uci_id': 189, 'name': 'Parkinsons Telemonitoring', 'repository_url': 'https://archive.ics.uci.edu/dataset/189/parkinsons+telemonitoring', 'data_url': 'https://archive.ics.uci.edu/static/public/189/data.csv', 'abstract': "Oxford Parkinson's Disease Telemonitoring Dataset", 'area': 'Life', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 5875, 'num_features': 26, 'attribute_types': ['Integer', 'Real'], 'target_col': ['motor_UPDRS', 'total_UPDRS'], 'index_col': ['subject#'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Thu Aug 03 2023', 'dataset_doi': '10.24432/C5ZS3N', 'creators': ['Athanasios Tsanas', 'Max Little'], 'intro_paper': {'title': "Accurate Telemonitoring of Parkinson's Disease Progression by Noninvasive Speech Tests", 'authors': 'A. Tsanas, Max A. Little, P. McSharry, L. Ramig', 'published_in': 'IEEE Transactions on Biomedical Engineering', 'year': 2010, 'url': 'https://www.semanticscholar.org/paper/1fdf33b6d8b1bdb38866ba824c1dcaecdfb6bdd6', 'doi': None}, 'additional_info': {'summary': "This dataset is composed of a range of biomedical voice measurements from 42 people with early-stage Parkinson's disease recruited to a six-month trial of a telemonitoring device for remote symptom progression monitoring. The recordings were automatically captured in the patient's homes.\r\n\r\nColumns in the table contain subject number, subject age, subject gender, time interval from baseline recruitment date, motor UPDRS, total UPDRS, and 16 biomedical voice measures. Each row corresponds to one of 5,875 voice recording from these individuals. The main aim of the data is to predict the motor and total UPDRS scores ('motor_UPDRS' and 'total_UPDRS') from the 16 voice measures.\r\n\r\nThe data is in ASCII CSV format. The rows of the CSV file contain an instance corresponding to one voice recording. There are around 200 recordings per patient, the subject number of the patient is identified in the first column. For further information or to pass on comments, please contact Athanasios Tsanas (tsanasthanasis@gmail.com) or Max Little (littlem@physics.ox.ac.uk).\r\n\r\nFurther details are contained in the following reference -- if you use this dataset, please cite:\r\nAthanasios Tsanas, Max A. Little, Patrick E. McSharry, Lorraine O. Ramig (2009),\r\n'Accurate telemonitoring of Parkinson’s disease progression by non-invasive speech tests',\r\nIEEE Transactions on Biomedical Engineering (to appear).\r\n\r\nFurther details about the biomedical voice measures can be found in:\r\nMax A. Little, Patrick E. McSharry, Eric J. Hunter, Lorraine O. Ramig (2009), \r\n'Suitability of dysphonia measurements for telemonitoring of Parkinson's disease', \r\nIEEE Transactions on Biomedical Engineering, 56(4):1015-1022\r\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'software_available': None, 'used_for': None, 'attribute_info': "subject# - Integer that uniquely identifies each subject\r\nage - Subject age\r\nsex - Subject gender '0' - male, '1' - female\r\ntest_time - Time since recruitment into the trial. The integer part is the number of days since recruitment. \r\nmotor_UPDRS - Clinician's motor UPDRS score, linearly interpolated\r\ntotal_UPDRS - Clinician's total UPDRS score, linearly interpolated\r\nJitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP - Several measures of variation in fundamental frequency\r\nShimmer,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA - Several measures of variation in amplitude\r\nNHR,HNR - Two measures of ratio of noise to tonal components in the voice\r\nRPDE - A nonlinear dynamical complexity measure\r\nDFA - Signal fractal scaling exponent\r\nPPE - A nonlinear measure of fundamental frequency variation \r\n", 'citation': None}}
             name     role        type demographic  \
0        subject#       ID     Integer        None
1             age  Feature     Integer         Age
2       test_time  Feature  Continuous        None
3       Jitter(%)  Feature  Continuous        None
4     Jitter(Abs)  Feature  Continuous        None
5      Jitter:RAP  Feature  Continuous        None
6     Jitter:PPQ5  Feature  Continuous        None
7      Jitter:DDP  Feature  Continuous        None
8         Shimmer  Feature  Continuous        None
9     Shimmer(dB)  Feature  Continuous        None
10   Shimmer:APQ3  Feature  Continuous        None
11   Shimmer:APQ5  Feature  Continuous        None
12  Shimmer:APQ11  Feature  Continuous        None
13    Shimmer:DDA  Feature  Continuous        None
14            NHR  Feature  Continuous        None
15            HNR  Feature  Continuous        None
16           RPDE  Feature  Continuous        None
17            DFA  Feature  Continuous        None
18            PPE  Feature  Continuous        None
19    motor_UPDRS   Target  Continuous        None
20    total_UPDRS   Target  Continuous        None
21            sex  Feature      Binary         Sex

                                          description units missing_values
0       Integer that uniquely identifies each subject  None             no
1                                         Subject age  None             no
2   Time since recruitment into the trial. The int...  None             no
3   Several measures of variation in fundamental f...  None             no
4   Several measures of variation in fundamental f...  None             no
5   Several measures of variation in fundamental f...  None             no
6   Several measures of variation in fundamental f...  None             no
7   Several measures of variation in fundamental f...  None             no
8          Several measures of variation in amplitude  None             no
9          Several measures of variation in amplitude  None             no
10         Several measures of variation in amplitude  None             no
11         Several measures of variation in amplitude  None             no
12         Several measures of variation in amplitude  None             no
13         Several measures of variation in amplitude  None             no
14  Two measures of ratio of noise to tonal compon...  None             no
15  Two measures of ratio of noise to tonal compon...  None             no
16           A nonlinear dynamical complexity measure  None             no
17                    Signal fractal scaling exponent  None             no
18  A nonlinear measure of fundamental frequency v...  None             no
19  Clinician's motor UPDRS score, linearly interp...  None             no
20  Clinician's total UPDRS score, linearly interp...  None             no
21               Subject sex '0' - male, '1' - female  None             no

In [18]:
X

,age,test_time,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,Shimmer,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,sex
0,72,5.6431,0.00662,0.000034,0.00401,0.00317,0.01204,0.02565,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006,0
1,72,12.6660,0.00300,0.000017,0.00132,0.00150,0.00395,0.02024,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810,0
2,72,19.6810,0.00481,0.000025,0.00205,0.00208,0.00616,0.01675,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014,0
3,72,25.6470,0.00528,0.000027,0.00191,0.00264,0.00573,0.02309,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277,0
4,72,33.6420,0.00335,0.000020,0.00093,0.00130,0.00278,0.01703,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,61,142.7900,0.00406,0.000031,0.00167,0.00168,0.00500,0.01896,0.160,0.00973,0.01133,0.01549,0.02920,0.025137,22.369,0.64215,0.55314,0.21367,0
5871,61,149.8400,0.00297,0.000025,0.00119,0.00147,0.00358,0.02315,0.215,0.01052,0.01277,0.01904,0.03157,0.011927,22.886,0.52598,0.56518,0.12621,0
5872,61,156.8200,0.00349,0.000025,0.00152,0.00187,0.00456,0.02499,0.244,0.01371,0.01456,0.01877,0.04112,0.017701,25.065,0.47792,0.57888,0.14157,0
5873,61,163.7300,0.00281,0.000020,0.00128,0.00151,0.00383,0.01484,0.131,0.00693,0.00870,0.01307,0.02078,0.007984,24.422,0.56865,0.56327,0.14204,0
5874,61,170.7300,0.00282,0.000021,0.00135,0.00166,0.00406,0.01907,0.171,0.00946,0.01154,0.01470,0.02839,0.008172,23.259,0.58608,0.57077,0.15336,0

In [30]:
list[38]

58

In [31]:
import os
import pandas as pd
from ucimlrepo import fetch_ucirepo

# Diretório para salvar os datasets
save_dir = '/home/daniel/source/uci/datasets'

# Loop pelos datasets
for lista in list[101:102]:
    print(lista)

    # Importa o dataset
    heart_disease = fetch_ucirepo(id=lista)
    # Alternativamente: fetch_ucirepo(name='Heart Disease')

    # Acessa os dados
    #x = heart_disease.data.features
    #y = heart_disease.data.targets
    z = heart_disease.data.original

    # Converte para DataFrames do pandas
    #x_df = pd.DataFrame(x, columns=heart_disease.feature_names)
    #y_df = pd.DataFrame(y, columns=['Target'])
    z_df = pd.DataFrame(z, columns=heart_disease.target_names)

    # Cria o diretório se não existir
    os.makedirs(save_dir, exist_ok=True)

    # Salva os DataFrames como CSV
    #x_df.to_csv(os.path.join(save_dir, f"{lista}_features.csv"), index=False)
    #y_df.to_csv(os.path.join(save_dir, f"{lista}_targets.csv"), index=False)
    z_df.to_csv(os.path.join(save_dir, f"{lista}_original.csv"), index=False)

242

In [9]:
from ucimlrepo import fetch_ucirepo, list_available_datasets

# import dataset
heart_disease = fetch_ucirepo(id=1)
# alternatively: fetch_ucirepo(name='Heart Disease')

# access data
X = heart_disease.data.features
y = heart_disease.data.targets
# train model e.g. sklearn.linear_model.LinearRegression().fit(X, y)

# access metadata
print(heart_disease.metadata.uci_id)
print(heart_disease.metadata.num_instances)
print(heart_disease.metadata.additional_info.summary)

# access variable info in tabular format
print(heart_disease.variables)

1
4177
Predicting the age of abalone from physical measurements.  The age of abalone is determined by cutting the shell through the cone, staining it, and counting the number of rings through a microscope -- a boring and time-consuming task.  Other measurements, which are easier to obtain, are used to predict the age.  Further information, such as weather patterns and location (hence food availability) may be required to solve the problem.

From the original data examples with missing values were removed (the majority having the predicted value missing), and the ranges of the continuous values have been scaled for use with an ANN (by dividing by 200).
             name     role         type demographic  \
0             Sex  Feature  Categorical        None
1          Length  Feature   Continuous        None
2        Diameter  Feature   Continuous        None
3          Height  Feature   Continuous        None
4    Whole_weight  Feature   Continuous        None
5  Shucked_weight  Feature   Continuous        None
6  Viscera_weight  Feature   Continuous        None
7    Shell_weight  Feature   Continuous        None
8           Rings   Target      Integer        None

                   description  units missing_values
0         M, F, and I (infant)   None             no
1    Longest shell measurement     mm             no
2      perpendicular to length     mm             no
3           with meat in shell     mm             no
4                whole abalone  grams             no
5               weight of meat  grams             no
6  gut weight (after bleeding)  grams             no
7            after being dried  grams             no
8  +1.5 gives the age in years   None             no

In [11]:
X

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [13]:
y

      Rings
0        15
1         7
2         9
3        10
4         7
...     ...
4172     11
4173     10
4174      9
4175     10
4176     12

[4177 rows x 1 columns]